version: '3.9'
services:
  backend:
    build:
      context: ./server
    container_name: backend-container
    ports:
      - '9876:8080'
    environment:
      PORT: 8080
      NODE_ENV: 'development'
      REDIS_SERVICE: 'ON'
      REDIS_INDUSTRY_LIST: 'ON'
      MONGO_URI: 'mongodb://root:rootpassword@mongodb_server:27017/tms?authSource=admin'
      REDIS_URL: redis://redis-server:6379
      ES_URL: http://es01:9200
      ES_USERNAME: elastic
      ES_PASSWORD: elastic-tms
    volumes:
      - ./server:/tms-server
    depends_on:
      - redis-server
      - mongodb_server
      - es01
    restart: always

  frontend:
    build:
      context: ./client
    container_name: frontend-container
    ports:
      - '8000:8000'
    environment:
      VITE_SERVER_URL: 'http://localhost:9876'

  redis-server:
    image: redis:alpine
    ports:
      - '6379:6379'
    container_name: 'redis-container'

  mongodb_server:
    image: mongo:jammy
    restart: always
    container_name: mongodb_server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - 'mongodb_server:/data/db'

  es01:
    # depends_on:
    #   setup:
    #     condition: service_healthy
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: es01
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
    # - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - node.name=es01
      - cluster.name=docker
      - discovery.type=single-node
      - ELASTIC_PASSWORD=elastic-tms
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true

      # - xpack.security.http.ssl.enabled=false
      # - xpack.security.http.ssl.key=certs/es01.key
      # - xpack.security.http.ssl.certificate=certs/es01.crt
      # - xpack.security.http.ssl.certificate_authorities=certs/ca.crt

      # - xpack.security.transport.ssl.enabled=true
      # - xpack.security.transport.ssl.key=certs/es01.key
      # - xpack.security.transport.ssl.certificate=certs/es01.crt
      # - xpack.security.transport.ssl.certificate_authorities=certs/ca.crt
      # - xpack.security.transport.ssl.verification_mode=certificate
      # - xpack.license.self_generated.type=basic
    mem_limit: 1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # healthcheck:
    #   test:
    #     [
    #       'CMD-SHELL',
    #       "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
    #     ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 120
networks:
  elastic:
    driver: bridge

volumes:
  mongodb_server: {}
